"""Ratified authority_effect additions — AUTO-GENERATED. Do not hand-edit.

Generated by `labelwatch authority-effect-promote`. Manual edits will be
overwritten on the next promotion run. To add an entry by hand, put it in
label_family.AUTHORITY_EFFECT_MAP directly; the hand-authored map always
wins on conflict (label_family imports this overlay with setdefault).

Provenance (cumulative across all promotion runs):
  (none)
"""

AUTHORITY_EFFECT_ADDITIONS: dict[str, str] = {}

LABELER_DEFAULT_EFFECT_ADDITIONS: dict[str, str] = {}
